apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ include "btrfs-csi.driverName" . }}
  labels:
    {{- include "btrfs-csi.labels" . | nindent 4 }}
spec:
  attachRequired: false
  podInfoOnMount: false
  volumeLifecycleModes:
    - Persistent
  fsGroupPolicy: File
  requiresRepublish: false
  storageCapacity: true
  tokenRequests: []
  seLinuxMount: false
