apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: btrfs.csi.k8s.io
spec:
  attachRequired: false
  podInfoOnMount: false
  volumeLifecycleModes:
    - Persistent
  fsGroupPolicy: File
  requiresRepublish: false
  storageCapacity: true
  tokenRequests: []
  seLinuxMount: false
