apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: btrfs-csi-driver
  namespace: kube-system
  labels:
    app: btrfs-csi-driver
spec:
  selector:
    matchLabels:
      app: btrfs-csi-driver
  template:
    metadata:
      labels:
        app: btrfs-csi-driver
    spec:
      serviceAccountName: btrfs-csi-driver
      hostNetwork: true
      hostPID: true
      containers:
        - name: btrfs-csi-driver
          image: localhost:5000/btrfs-csi:latest
          imagePullPolicy: Never
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
            - "--v=5"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: kubelet-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
            - name: plugin-dir
              mountPath: /csi
            - name: host-root
              mountPath: /host
              mountPropagation: "Bidirectional"
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            capabilities:
              # drop all capabilities, except:
              drop: ["ALL"]
              # except:
              add:
                - "SYS_ADMIN" # required for `mount` and `btrfs subvolume` commands
                - "SYS_CHROOT" # required for `chroot` command
            runAsUser: 0
            runAsGroup: 0
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
              cpu: "100m"
        - name: node-driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.14.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/btrfs.csi.k8s.io/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
            - name: kubelet-dir
              mountPath: /var/lib/kubelet
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
              cpu: "100m"
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v5.3.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
            - "--leader-election=true"
            - "--feature-gates=Topology=true"
            - "--node-deployment"
            - "--node-deployment-base-delay=20s"
            - "--node-deployment-max-delay=60s"
            - "--strict-topology"
            - "--extra-create-metadata"
            - "--leader-election-namespace=$(NAMESPACE)"
            - "--enable-capacity"
            - "--capacity-ownerref-level=1"
          env:
            - name: ADDRESS
              value: unix:///csi/csi.sock
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
              cpu: "100m"
        - name: csi-resizer
          image: registry.k8s.io/sig-storage/csi-resizer:v1.13.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
            - "--leader-election=true"
            - "--leader-election-namespace=$(NAMESPACE)"
          env:
            - name: ADDRESS
              value: unix:///csi/csi.sock
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
              cpu: "100m"
      volumes:
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/btrfs.csi.k8s.io
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
        - name: host-root
          hostPath:
            path: /
            type: Directory
      tolerations:
        - operator: Exists
          effect: NoSchedule
        - operator: Exists
          effect: NoExecute
      nodeSelector:
        kubernetes.io/os: linux
