name: Publish Helm chart for CSI driver

on:
  push:
    # Publish semver tags as releases.
    tags: [ '([0-9]+)\.([0-9]+)\.([0-9]+)(-[a-zA-Z0-9]+)?' ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Chart's AppVersion
        run: |
          cd deploy/helm/btrfs-csi
          sed -i "s/REPLACE_APP_VERSION/${{ github.ref_name }}/" Chart.yaml

      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.5.0
        with:
          name: btrfs-csi
          path: deploy/helm/btrfs-csi
          repository: ${{ github.repository }}/charts
          tag: ${{ github.ref_name }}
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
